### PR TITLE
Features Updates

### PR DESCRIPTION
**Pull request by lunestelle**
### **Changes Made**
- Maintenance Log automatic selection of driver name based on the selected tricycle cin.
- Maintenance Tracker update
   - Added `All` Filter
   - Added New Column --- `Expense Year` if the selected filter is `All`
   - Updated the CSV export so that it will include the `Expense Year` if the selected filter is `All`
- Updated the Verify button on the Manage Account page
- Fix issues with the appointment notification
- Print & Download PDF be accessible on all `appointment statuses (Pending, Approved, On Process, Completed, Rejected)`. 
- Deleted Unused Files `"edit_tricycles.php" and "Edit_tricycles.php"`.
- Added `"All Filter"` on the appointment reports feature.
- Added `"Date Range Filter"` on the appointments/appointments approval feature, this filter also automatically be reflected on the export. 
- Implemented `"Send Us A Message"` functionality
   - Added a new feature `"Inquiries"` which is only available to the admin users.
   - Once the admin has a response and sent it, `it will either send an SMS or Email depending on what they have submitted on the "Sent Us A Message"`

**❗️ Please update the UI of the modals used in here**
Inquiries Feature

**View Message Modal (Example Modal):**
image

**❗️ Please update the UI**
Date Range Filter

> **💥BIG CHANGES MADE -- _(Please check thoroughly and see if there are any issues)_**
> - Make the Actions on the tricycles show one or more statuses.
>    - Fix Issues occurred due to updates made.
>    - ❗️ Added New Email and SMS Notification when the tricycle status is updated to `Dropped`
>    -  Updated the flow of the appointment process wherein the user applied for `Renewal or Change Motor`. Once the appointment process is completed, the status on the tricycle `"Renewal Required"` or `"Change Motor Required"` will be removed or deleted on that specific tricycle status and only the `"Active"` status will remain. _(Please check also the part where the user can edit the appointment)_
> - The Appointment Process Flow has been updated where when the `user selects the Appointment Type "Renewal of Franchise", "Change of Motorcycle", and "Transfer of Ownership"` the user is asked to `select a Tricycle CIN`.
>
> New Appointment Process Image
>
> - Appointment Tricycle Application Form is automatically filled in based on the` Tricycle CIN` selected.
> 
> Updated Tricycle Application Form
>

**❗️ NOTE:**
- There are updates on the database, please update the documents and your SQL database for localhost testing.
- [sakaycle (01-20-24).zip](https://github.com/lunestelle/PHP_Sakaycle/files/13995042/sakaycle.01-20-24.zip)

### CODE REVIEW

**Comment by shayiii0714** [comment]
## 👍 NO ISSUE: 😃 
💹 Maintenance Log automatic selection of driver name based on the selected tricycle cin.
💹 Maintenance Tracker update
   -  Added All Filter
   - Added New Column --- Expense Year if the selected filter is All
   - Updated the CSV export so that it will include the Expense Year if the selected filter is All

💹  Updated the Verify button on the Manage Account page
💹 Print & Download PDF be accessible on all appointment statuses `(Pending, Approved, On Process, Completed, Rejected).`
💹 Added "All Filter" on the appointment reports feature.
💹 Added "Date Range Filter" on the appointments/appointments approval feature, this filter also automatically be reflected on the export.
💹 Implemented "Send Us A Message" functionality

   - Added a new feature "Inquiries" which is only available to the admin users
   - Once the admin has a response and sent it, it will either send an SMS or Email depending on what they have submitted on the "Sent Us A Message"

###  Will check this again for new user
💹 Maintenance Log automatic selection of driver name based on the selected tricycle cin.
💹 Appointment Tricycle Application Form is automatically filled in based on the Tricycle CIN selected. 
💹 The Appointment Process Flow has been updated where when the user selects the Appointment Type `"Renewal of Franchise", "Change of Motorcycle", and "Transfer of Ownership"` the user is asked to select a Tricycle CIN.
💹  Added New Email and SMS Notification when the tricycle status is updated to Dropped
💹 Updated the flow of the appointment process wherein the user applied for Renewal or Change Motor. Once the appointment process is completed, the status on the tricycle "Renewal Required" or "Change Motor Required" will be removed or deleted on that specific tricycle status and only the "Active" status will remain. (Please check also the part where the user can edit the appointment)




## DONE UPDATE:
💹 Filter Button
💹 Update the column on `Print` and `Download PDF`
💹 Update the column on tricycle page `update status`
💹 Messages Modal UI
   - Read Message Modal
   - View Response Modal
   - Response to Inquiry Modal

## 🛠️ TO FIX/UPDATE: 🛠️ 

- [ ] Update the order on `Appointments`, `Appoinment Approval`, `Inquiries` index page tables. It should display the latest data on top of the data.
- [ ] The added column for `Print` , `Download PDF` , and `update status` should not visible to operators
- [ ] For New user [ the appointment lists of all other operators should not visible to other operators]
   - image

- [ ] Cannot set a new appoint [New User] Ps: Cheack on your local maybe the error occur on my end only.
   - image

**Comment by lunestelle** [comment]
## 🛠️ FIXED 🛠️ 

> - [ ] Update the order on `Appointments`, `Appoinment Approval`, `Inquiries` index page tables. It should display the latest data on top of the table.
> - [ ] The added column for `Print` , `Download PDF` , and `update status` should not visible to operators
> - [ ] For New user [ the appointment lists of all other operators should not visible to other operators]
>    - image
>  
> - [ ] On `Maintenance Tracker` viewing page it should display all maintenance logs of a one Tricycle and has sum of the total costs.
>    - It should divided into YEAR expenses
>    - Should look like this:
>       - maintenance-tracker
> 
> - [ ] Cannot set a new appointment [New User] Ps: Cheack on your local maybe the error occur on my end only.
>    - image
>

**Comment by shayiii0714** [comment]
## 👍 NO ISSUE: 😃

💹 Maintenance Log automatic selection of driver name based on the selected tricycle cin.
💹 Appointment Tricycle Application Form is automatically filled in based on the `Tricycle CIN` selected.
💹 The Appointment Process Flow has been updated where when the user selects the Appointment Type `"Renewal of Franchise"`, `"Change of Motorcycle"`, and `"Transfer of Ownership" `the user is asked to select a Tricycle CIN.

💹 Updated the flow of the appointment process wherein the user applied for Renewal or Change Motor. Once the appointment process is completed, the status on the tricycle` "Renewal Required" or "Change Motor Required"` will be **removed or deleted** on that specific tricycle status and only the "Active" status will remain. (Please check also the part where the user can edit the appointment)

💹 Can set a new appointment [New User] Ps: Check on your local maybe the error occur on my end only.
💹 Update the order on Appointments, Appoinment Approval, Inquiries index page tables. It should display the latest data on top of the table.
💹 The added column for `Print` , `Download PDF`, and `update status` should not visible to operators
💹 For New user [ the appointment lists of all other operators should not visible to other operators
On Maintenance Tracker viewing page it should display all maintenance logs of a one Tricycle and has sum of the total costs.
💹 Updated the Maintenance tracker implementation
     - On Maintenance Tracker viewing page it should display all maintenance logs of a one Tricycle and has sum of the total costs.
     - It should divided into YEAR expenses
     - On All filter or when user still havent selected will now shows data of tricycle cin na dili mag repeat as table.
     - 
     
 ## DONE UPDATE:
 💹 UI on view calculations `maintenance tracker`
## TO CHECK:
Added New Email and SMS Notification when the tricycle status is updated to Dropped

## 🛠️TO FIX:🛠️

- [ ] ❌Can log a maintenance without uploading a receipt. It should not log a maintenance without a receipt.

- [ ] ❌The data given in `date` and `time` are incorrect. Please check on your end (Basin sa ako ra ba).

image

- [ ] ❌I think when the appointment status == `approved` the operator is unable to edit his/her appointment.

image

- [ ] ❌[**NEW USER**] The completed `New Franchise` appointment didn't show the data on `Tricyles` index pages on `ADMIN` and `OPERATOR`. See Photos  below :👇

image
image
image

**Comment by lunestelle** [comment]
## 🛠️FIXED:🛠️

> - [x] ❌Can log a maintenance without uploading a receipt. It should not log a maintenance without a receipt.
> - [x] ❌ Update the order on the `Inquiries`  index page tables. It should display the latest data on top of the table.
> image
> 
> - [ ] ❌The data given in `date` and `time` are incorrect. Please check on your end (Basin sa ako ra ba). 
>     - I have checked this on my end, and it was correct 🤔 
>
> image
> 
> - [ ] ❌I think when the appointment status == `approved` the operator is unable to edit his/her appointment.
> 
> image
> 
> - [ ] ❌[**NEW USER**] The completed `New Franchise` appointment didn't show the data on `Tricyles` index pages on `ADMIN` and `OPERATOR`. See Photos  below :👇
> 
> image
> image
> image
> 
> 
>

**Comment by lunestelle** [comment]
**Implemented Badge for Inquiries, Appointments (Operator), and Appointment Approval (Admin)**

- Inquiries badge counts the Unread messages
- Appointments (Operator) and Appointment Approval (Admin) counts the pending appointments


image

**Comment by shayiii0714** [comment]
## 👍 NO ISSUE: 😃
💹 Can log a maintenance without uploading a receipt. It should not log a maintenance without a receipt.
💹 Update the order on the Inquiries index page tables. It should display the latest data on top of the table.
💹 The data given in date and time are incorrect. Please check on your end (Basin sa ako ra ba).
💹 If the appointment status == approved the operator is unable to edit his/her appointment.
💹 [NEW USER] The completed New Franchise appointment didn't show the data on Tricyles index pages on `ADMIN` and `OPERATOR`.
💹 New Email and SMS Notification when the tricycle status is updated to Dropped

💹 **Implemented Badge for Inquiries, Appointments (Operator), and Appointment Approval (Admin)**

- Inquiries badge counts the Unread messages
- Appointments (Operator) and Appointment Approval (Admin) counts the pending appointments

**Pull request merged**
